export interface Milestone {
  id: string;
  time: number; // seconds relative to T-0
  label: string;
  description: string;
  type: 'countdown' | 'ascent' | 'mission';
}

export const MISSION_MILESTONES: Milestone[] = [
  // Countdown (L- Minus)
  { id: 'l-49h50m', time: -179400, label: 'Launch Team Arrives', description: 'Launch team arrives to stations for the countdown.', type: 'countdown' },
  { id: 'l-49h40m', time: -178800, label: 'Countdown Begins', description: 'Countdown clock begins. LOX/LH2 system preparations start.', type: 'countdown' },
  { id: 'l-45h30m', time: -163800, label: 'Orion Power Up', description: 'Orion spacecraft powered up.', type: 'countdown' },
  { id: 'l-42h20m', time: -152400, label: 'Core Stage Power Up', description: 'Core stage powered up.', type: 'countdown' },
  { id: 'l-42h10m', time: -151800, label: 'ICPS Power Up', description: 'Interim cryogenic propulsion stage (ICPS) powered up.', type: 'countdown' },
  { id: 'l-39h45m', time: -143100, label: 'RS-25 Prep', description: 'Final preparations of the four RS-25 engines.', type: 'countdown' },
  { id: 'l-34h45m', time: -125100, label: 'ICPS Power Down', description: 'ICPS is powered down.', type: 'countdown' },
  { id: 'l-33h30m', time: -120600, label: 'Orion Battery Charge', description: 'Charge Orion flight batteries to 100%.', type: 'countdown' },
  { id: 'l-31h30m', time: -113400, label: 'Core Stage Battery Charge', description: 'Charge core stage flight batteries.', type: 'countdown' },
  { id: 'l-20H15M', time: -72900, label: 'ICPS Power Up', description: 'ICPS is powered up for launch.', type: 'countdown' },
  { id: 'l-15h30m', time: -55800, label: 'Personnel Evacuation', description: 'All non-essential personnel leave Launch Complex 39B.', type: 'countdown' },
  { id: 'l-14h15m', time: -51300, label: 'GN2 Changeover', description: 'Air-to-gaseous nitrogen (GN2) changeover and rocket cavity inerting.', type: 'countdown' },
  { id: 'l-13h15m', time: -47700, label: 'GLS Activation', description: 'Ground launch sequencer (GLS) activation.', type: 'countdown' },
  { id: 'l-12h35m', time: -45300, label: 'Built-in Hold (2H45M)', description: '2-hour 45-minute built in countdown hold begins.', type: 'countdown' },
  { id: 'l-10h50m', time: -39000, label: 'Tanking Go/No-Go', description: 'Launch team decides "go" or "no-go" to begin tanking. Orion cold soak begins.', type: 'countdown' },
  { id: 'l-10h40m', time: -38400, label: 'Chilldown', description: 'Core stage LOX transfer line and LH2 chilldown begins.', type: 'countdown' },
  { id: 'l-10h25m', time: -37500, label: 'MPS Chilldown', description: 'Core stage LOX main propulsion system chilldown.', type: 'countdown' },
  { id: 'l-9h55m', time: -35700, label: 'Slow Fill Start', description: 'Core stage LH2 slow fill start.', type: 'countdown' },
  { id: 'l-9h50m', time: -35400, label: 'Resume T-Clock', description: 'Resume T-Clock from T-8H10M.', type: 'countdown' },
  { id: 'l-9h40m', time: -34800, label: 'LOX Slow Fill', description: 'Core stage LOX slow fill.', type: 'countdown' },
  { id: 'l-9h30m', time: -34200, label: 'LOX Fast Fill', description: 'Core stage LOX fast fill.', type: 'countdown' },
  { id: 'l-9h25m', time: -33900, label: 'LH2 Fast Fill', description: 'Core stage LH2 fast fill.', type: 'countdown' },
  { id: 'l-9h05m', time: -32700, label: 'ICPS LH2 Chilldown', description: 'ICPS LH2 chilldown.', type: 'countdown' },
  { id: 'l-8h30m', time: -30600, label: 'ICPS LH2 Fast Fill', description: 'ICPS LH2 fast fill start.', type: 'countdown' },
  { id: 'l-8h', time: -28800, label: 'LH2 Topping', description: 'Core stage LH2 topping.', type: 'countdown' },
  { id: 'l-7h55m', time: -28500, label: 'LH2 Replenish', description: 'Core stage LH2 replenish.', type: 'countdown' },
  { id: 'l-7h45m', time: -27900, label: 'ICPS Vent Test', description: 'ICPS LH2 vent and relief test.', type: 'countdown' },
  { id: 'l-7h20m', time: -26400, label: 'ICPS LH2 Topping', description: 'ICPS LH2 tank topping start.', type: 'countdown' },
  { id: 'l-7h05m', time: -25500, label: 'ICPS LH2 Replenish', description: 'ICPS LH2 replenish.', type: 'countdown' },
  { id: 'l-6h40m', time: -24000, label: 'Comm Activation', description: 'Orion communications system activated. Core stage LOX topping.', type: 'countdown' },
  { id: 'l-6h10m', time: -22200, label: 'Pad Rescue/Closeout', description: 'Stage pad rescue and closeout crew assemble.', type: 'countdown' },
  { id: 'l-6h05m', time: -21900, label: 'LOX Replenish', description: 'Core stage LOX replenish.', type: 'countdown' },
  { id: 'l-6h', time: -21600, label: 'Crew Weather Brief', description: 'Flight crew weather brief.', type: 'countdown' },
  { id: 'l-5h45m', time: -20700, label: 'ICPS LOX Vent Test', description: 'ICPS LOX vent and relief test.', type: 'countdown' },
  { id: 'l-5h30m', time: -19800, label: 'ICPS LOX Topping', description: 'ICPS LOX topping.', type: 'countdown' },
  { id: 'l-5h10m', time: -18600, label: 'Built-in Hold (1H10M)', description: 'Start 1-hour 10-minute built in hold. All stages replenish.', type: 'countdown' },
  { id: 'l-4h40m', time: -16800, label: 'Crew to Pad', description: 'Flight crew deployment to pad.', type: 'countdown' },
  { id: 'l-4h', time: -14400, label: 'Crew Boarding', description: 'Flight crew board Orion.', type: 'countdown' },
  { id: 'l-3h40m', time: -13200, label: 'Hatch Closure', description: 'Crew module hatch preps and closure.', type: 'countdown' },
  { id: 'l-3h10m', time: -11400, label: 'Hatch Checks', description: 'Counterbalance mechanism hatch sealpress decay checks.', type: 'countdown' },
  { id: 'l-2h20m', time: -8400, label: 'Hatch Closeouts', description: 'Crew module hatch service panel install/closeouts.', type: 'countdown' },
  { id: 'l-1h40m', time: -6000, label: 'LAS Hatch Closure', description: 'Launch abort system (LAS) hatch closure for flight.', type: 'countdown' },
  { id: 'l-1h10m', time: -4200, label: 'Director Brief', description: 'Launch director brief – rocket & thermal protection system scan results.', type: 'countdown' },
  { id: 'l-50m', time: -3000, label: 'Final Briefing', description: 'Closeout crew departs. Final NASA test director briefing.', type: 'countdown' },
  { id: 'l-40m', time: -2400, label: 'Built-in Hold (30M)', description: 'Built in 30-minute countdown hold begins.', type: 'countdown' },
  { id: 'l-25m', time: -1500, label: 'Comm Loop Transition', description: 'Transition team to Orion to Earth communication loop.', type: 'countdown' },
  { id: 'l-17m', time: -1020, label: 'Final Poll', description: 'Launch director polls team to ensure they are "go" for launch.', type: 'countdown' },
  { id: 'l-15m', time: -900, label: 'Visors Down', description: 'Flight crew visors down.', type: 'countdown' },
  { id: 'l-14m', time: -840, label: 'Purge Verification', description: 'Flight crew short purge verification.', type: 'countdown' },

  // Terminal Count (T- Minus)
  { id: 't-10m', time: -600, label: 'Terminal Count Start', description: 'GLS initiates terminal count.', type: 'countdown' },
  { id: 't-8m', time: -480, label: 'Arm Retract', description: 'Crew Access Arm retract.', type: 'countdown' },
  { id: 't-6m', time: -360, label: 'Internal Power', description: 'Orion set to internal power. Ascent pyros armed.', type: 'countdown' },
  { id: 't-5m57s', time: -357, label: 'LH2 Terminate', description: 'Core stage LH2 terminate replenish.', type: 'countdown' },
  { id: 't-5m20s', time: -320, label: 'LAS Available', description: 'Launch Abort System capability is available.', type: 'countdown' },
  { id: 't-4m40s', time: -280, label: 'High Flow Bleed', description: 'GLS go for LH2 high flow bleed check.', type: 'countdown' },
  { id: 't-4m30s', time: -270, label: 'FTS Armed', description: 'Flight termination system armed.', type: 'countdown' },
  { id: 't-4m', time: -240, label: 'APU Start', description: 'Core Stage APU starts. LOX terminate replenish.', type: 'countdown' },
  { id: 't-3m30s', time: -210, label: 'ICPS LOX Terminate', description: 'ICPS LOX terminate replenish.', type: 'countdown' },
  { id: 't-3m10s', time: -190, label: 'Purge Sequence 4', description: 'GLS go for purge sequence 4.', type: 'countdown' },
  { id: 't-2m02s', time: -122, label: 'ICPS Internal Power', description: 'ICPS switches to internal battery power.', type: 'countdown' },
  { id: 't-2m', time: -120, label: 'Booster Internal Power', description: 'Booster switches to internal battery power.', type: 'countdown' },
  { id: 't-1m30s', time: -90, label: 'Core Internal Power', description: 'Core stage switches to internal power.', type: 'countdown' },
  { id: 't-1m20s', time: -80, label: 'ICPS Terminal Mode', description: 'ICPS enters terminal countdown mode.', type: 'countdown' },
  { id: 't-50s', time: -50, label: 'ICPS LH2 Terminate', description: 'ICPS LH2 terminate replenish.', type: 'countdown' },
  { id: 't-33s', time: -33, label: 'Automated Sequencer', description: 'GLS sends "go for automated launch sequencer" command.', type: 'countdown' },
  { id: 't-30s', time: -30, label: 'Core Stage Sequencer', description: 'Core stage flight computer to automated launching sequencer.', type: 'countdown' },
  { id: 't-12s', time: -12, label: 'Hydrogen Igniters', description: 'Hydrogen burn off igniters initiated.', type: 'countdown' },
  { id: 't-10s', time: -10, label: 'Engine Start Command', description: 'GLS sends the command for core stage engine start.', type: 'countdown' },
  { id: 't-6.36s', time: -6.36, label: 'RS-25 Startup', description: 'RS-25 engines startup.', type: 'countdown' },
  { id: 't-0', time: 0, label: 'Liftoff', description: 'Booster ignition, umbilical separation, and liftoff.', type: 'countdown' },

  // Ascent
  { id: 'a-00-09', time: 9, label: 'Tower Clear', description: 'SLS clears the launch tower and initiates roll/pitch maneuver.', type: 'ascent' },
  { id: 'a-00-56', time: 56, label: 'Supersonic', description: 'SLS reaches supersonic speed.', type: 'ascent' },
  { id: 'a-01-10', time: 70, label: 'Max Q', description: 'Maximum dynamic pressure.', type: 'ascent' },
  { id: 'a-02-08', time: 128, label: 'SRB Separation', description: 'Solid Rocket Booster separation.', type: 'ascent' },
  { id: 'a-03-18', time: 198, label: 'LAS Jettison', description: 'Launch abort system jettison.', type: 'ascent' },
  { id: 'a-08-06', time: 486, label: 'MECO', description: 'SLS core stage main engine cutoff.', type: 'ascent' },
  { id: 'a-08-18', time: 498, label: 'Core Separation', description: 'Core stage separates from ICPS (1381×17-mile orbit).', type: 'ascent' },
  { id: 'a-08-28', time: 508, label: 'Nozzle Extension', description: 'ICPS RL10 nozzle extension.', type: 'ascent' },
  { id: 'a-20-00', time: 1200, label: 'Solar Array Deploy', description: 'Orion solar arrays deploy.', type: 'ascent' },
  { id: 'a-49-00', time: 2940, label: 'Perigee Raise', description: 'Perigee raise maneuver (1381×115 statute miles).', type: 'ascent' },
  { id: 'a-01-47-57', time: 6477, label: 'Apogee Raise Burn', description: 'Apogee raise burn (43730×0 statute miles).', type: 'ascent' },
  { id: 'a-03-24-15', time: 12255, label: 'ICPS Separation', description: 'Orion separates from ICPS, proximity operations begin.', type: 'ascent' },
  { id: 'a-04-35-00', time: 16500, label: 'Prox Ops Conclude', description: 'Proximity operations conclude.', type: 'ascent' },
  { id: 'a-04-52-00', time: 17520, label: 'Upper Stage Separation', description: 'Orion upper stage separation burn.', type: 'ascent' },
  { id: 'a-05-00-00', time: 18000, label: 'ICPS Disposal', description: 'Disposal burn of ICPS into the Pacific Ocean.', type: 'ascent' },
  { id: 'a-05-04-00', time: 18240, label: 'CubeSats Deploy', description: 'CubeSats deploy at one minute intervals.', type: 'ascent' },
  { id: 'a-13-44-00', time: 49440, label: 'Perigee Raise Burn', description: 'Secondary perigee raise burn.', type: 'ascent' },

  // Mission
  { id: 'm-fd2-tli', time: 92220, label: 'TLI Burn', description: 'Translunar injection burn.', type: 'mission' },
  { id: 'm-fd2-otc', time: 170700, label: 'OTC Burn', description: 'Orbital Trajectory Correction Burn.', type: 'mission' },
  { id: 'm-fd3-otc1', time: 173220, label: 'OTC Burn #1', description: 'Orbital trajectory correction burn #1.', type: 'mission' },
  { id: 'm-fd3-cpr', time: 180300, label: 'CPR Demo', description: 'Crew CPR demonstration.', type: 'mission' },
  { id: 'm-fd3-comm', time: 192300, label: 'DSN Comm Test', description: 'Communications test through Deep Space Network.', type: 'mission' },
  { id: 'm-fd4-otc2', time: 259920, label: 'OTC Burn #2', description: 'Orbital trajectory correction burn #2.', type: 'mission' },
  { id: 'm-fd4-lunar-plan', time: 272400, label: 'Lunar Imaging Plan', description: 'Review lunar flyby imaging plan.', type: 'mission' },
  { id: 'm-fd5-suits', time: 333000, label: 'Suit Demo', description: 'Rapid spacesuits donning and pressurization demonstration.', type: 'mission' },
  { id: 'm-fd5-otc3', time: 364980, label: 'OTC Burn #3', description: 'Orbital trajectory correction burn #3.', type: 'mission' },
  { id: 'm-fd5-soi-entry', time: 370740, label: 'Lunar SOI Entry', description: 'Orion enters lunar sphere of influence.', type: 'mission' },
  { id: 'm-fd6-flyby-start', time: 424800, label: 'Lunar Flyby Start', description: 'Lunar flyby and observation begins.', type: 'mission' },
  { id: 'm-fd6-closest', time: 436980, label: 'Closest Approach', description: 'Closest approach to the Moon and max distance from Earth.', type: 'mission' },
  { id: 'm-fd7-soi-exit', time: 503220, label: 'Lunar SOI Exit', description: 'Orion exits lunar sphere of influence.', type: 'mission' },
  { id: 'm-fd7-science', time: 508200, label: 'Science Debrief', description: 'Lunar flyby science debrief.', type: 'mission' },
  { id: 'm-fd7-rtc1', time: 534180, label: 'RTC Burn #1', description: 'Return trajectory correction burn #1.', type: 'mission' },
  { id: 'm-fd8-rad', time: 611400, label: 'Radiation Demo', description: 'Radiation shielding demonstration.', type: 'mission' },
  { id: 'm-fd8-pilot', time: 620400, label: 'Manual Piloting', description: 'Manual piloting demonstration.', type: 'mission' },
  { id: 'm-fd9-garment', time: 688500, label: 'OIG Assessment', description: 'Orthostatic intolerance garment assessment.', type: 'mission' },
  { id: 'm-fd9-rtc2', time: 707580, label: 'RTC Burn #2', description: 'Return trajectory correction burn #2.', type: 'mission' },
  { id: 'm-fd10-rtc3', time: 765180, label: 'RTC Burn #3', description: 'Return trajectory correction burn #3.', type: 'mission' },
  { id: 'm-fd10-checklist', time: 772200, label: 'Entry Checklist', description: 'Crew begins working through entry checklist and donning suits.', type: 'mission' },
  { id: 'm-fd10-sep', time: 781980, label: 'Module Separation', description: 'Orion crew and service module separation.', type: 'mission' },
  { id: 'm-fd10-raise', time: 782160, label: 'CM Raise Burn', description: 'Crew module raise burn.', type: 'mission' },
  { id: 'm-fd10-entry', time: 783180, label: 'Entry Interface', description: 'Entry interface, 400,000 feet above Earth.', type: 'mission' },
  { id: 'm-fd10-splashdown', time: 783960, label: 'Splashdown', description: 'Splashdown in the Pacific Ocean.', type: 'mission' },
  { id: 'm-fd10-safing', time: 784380, label: 'RCS Safing', description: 'Crew module reaction control system safing.', type: 'mission' },
  { id: 'm-fd10-powerdown', time: 784860, label: 'Final Power Down', description: 'Orion Final power down.', type: 'mission' },
];

export const TELEMETRY_CONFIG = {
  altitude: { min: 0, max: 400000, unit: 'km', label: 'Altitude' },
  velocity: { min: 0, max: 40000, unit: 'km/h', label: 'Velocity' },
  fuel: { min: 0, max: 100, unit: '%', label: 'Propellant' },
  oxygen: { min: 0, max: 100, unit: '%', label: 'O2 Levels' },
};
